# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HeyPlease' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeyPlease
pod 'Firebase'
pod 'Firebase/Core' 
pod 'Firebase/Auth'
pod 'Firebase/DynamicLinks'
pod 'lottie-ios'

  target 'HeyPleaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HeyPleaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
